<?php
/**
 * WP Ultimo Autoloader Plugin
 *
 * Composer plugin that modifies the Jetpack autoloader classmap to prevent
 * autoloading when WP_ULTIMO_PLUGIN_FILE is defined but doesn't end with 'ultimate-multisite.php'.
 *
 * @package WP_Ultimo
 */

namespace WP_Ultimo\Composer;

use Composer\Composer;
use Composer\EventDispatcher\EventSubscriberInterface;
use Composer\IO\IOInterface;
use Composer\Plugin\PluginInterface;
use Composer\Script\Event;
use Composer\Script\ScriptEvents;

/**
 * Class WP_Ultimo_Autoloader_Plugin
 */
class WP_Ultimo_Autoloader_Plugin implements PluginInterface, EventSubscriberInterface {

	/**
	 * IO object.
	 *
	 * @var IOInterface
	 */
	private $io;

	/**
	 * Composer object.
	 *
	 * @var Composer
	 */
	private $composer;

	/**
	 * Activate plugin.
	 *
	 * @param Composer    $composer Composer object.
	 * @param IOInterface $io IO object.
	 */
	public function activate(Composer $composer, IOInterface $io) {
		$this->composer = $composer;
		$this->io       = $io;
	}

	/**
	 * Deactivate plugin.
	 *
	 * @param Composer    $composer Composer object.
	 * @param IOInterface $io IO object.
	 */
	public function deactivate(Composer $composer, IOInterface $io) {
		// Intentionally left empty.
	}

	/**
	 * Uninstall plugin.
	 *
	 * @param Composer    $composer Composer object.
	 * @param IOInterface $io IO object.
	 */
	public function uninstall(Composer $composer, IOInterface $io) {
		// Intentionally left empty.
	}

	/**
	 * Get subscribed events.
	 *
	 * @return array
	 */
	public static function getSubscribedEvents() {
		return array(
			ScriptEvents::POST_AUTOLOAD_DUMP => array(
				array('modifyJetpackAutoloader', -10), // Run after jetpack autoloader (priority -10)
			),
		);
	}

	/**
	 * Modify the Jetpack autoloader classmap for Ultimate Multisite.
	 *
	 * The root Composer configuration excludes MU-Migration from the classmap,
	 * but Jetpack Autoloader v5.0.17 does not honour that root-package setting.
	 * Remove those entries here until its upstream generator supports it.
	 *
	 * @param Event $event Script event object.
	 */
	public function modifyJetpackAutoloader(Event $event) {
		$config        = $this->composer->getConfig();
		$vendor_path   = $config->get('vendor-dir');
		$classmap_path = $vendor_path . '/composer/jetpack_autoload_classmap.php';

		if ( ! file_exists($classmap_path) ) {
			return;
		}

		$content = file_get_contents($classmap_path); // phpcs:ignore

		if (false === $content) {
			return;
		}

		$new_content = $this->exclude_mu_migration_from_jetpack_classmap($content);

		// Add the existing plugin-file guard only when it is not already present.
		if ( strpos($new_content, "defined('WP_ULTIMO_PLUGIN_FILE')") === false ) {
			// Find the opening PHP tag and add our check right after it.
			$search      = "<?php\n\n// This file `jetpack_autoload_classmap.php` was auto generated by automattic/jetpack-autoloader.";
			$replacement = "<?php\n\n// This file `jetpack_autoload_classmap.php` was auto generated by automattic/jetpack-autoloader.\nif (defined('WP_ULTIMO_PLUGIN_FILE') && substr(WP_ULTIMO_PLUGIN_FILE, -22) !== 'ultimate-multisite.php') {\n\treturn;\n}";

			$new_content = str_replace($search, $replacement, $new_content);
		}

		if ( $new_content !== $content ) {
			file_put_contents($classmap_path, $new_content); // phpcs:ignore
			$this->io->write('<info>Modified jetpack_autoload_classmap.php for Ultimate Multisite</info>');
		}
	}

	/**
	 * Remove MU-Migration entries from the generated Jetpack Autoloader map.
	 *
	 * The bundled WP-CLI polyfill intentionally defines global WP_CLI classes.
	 * Leaving it in a classmap means unrelated class_exists( 'WP_CLI' ) probes
	 * autoload the polyfill and mistake a web request for a real WP-CLI process.
	 *
	 * @param string $content Generated Jetpack Autoloader classmap content.
	 * @return string
	 */
	private function exclude_mu_migration_from_jetpack_classmap($content) {

		$pattern  = "/\n\t'[^']+' => array\(\n\t\t'version' => '[^']+',\n\t\t'path'\s*=> [^\n]*\\/inc\\/site-exporter\\/mu-migration\\/[^\n]*\n\t\),/";
		$filtered = preg_replace($pattern, '', $content);

		if ( ! is_string($filtered) ) {
			return $content;
		}

		if ( $filtered === $content && strpos($content, '/inc/site-exporter/mu-migration/') !== false ) {
			$this->io->write(
				'<warning>MU-Migration entries found in Jetpack classmap but the exclusion pattern did not match. The classmap format may have changed.</warning>'
			);
		}

		return $filtered;
	}
}
