<?php
/**
 * BerlinDB Dynamic Hooks Reference
 *
 * This file is auto-generated by generate-berlindb-hooks.php and exists solely
 * so that @10up/wp-hooks-documentor can discover the dynamic hooks fired by
 * BerlinDB's Query class. It is never loaded at runtime.
 *
 * @package WP_Ultimo
 * @subpackage Documentation
 * @since 2.3.0
 * @generated
 */

defined('ABSPATH') || exit;

// phpcs:disable -- This file is never executed; it only carries docblocks.

/*
 * ──────────────────────────────────────────────────────────────────────────────
 * The hooks below are dynamically fired by BerlinDB (vendor/berlindb/core/src/
 * Database/Query.php) for every registered model. They are grouped by model and
 * then by hook pattern.
 *
 * Patterns:
 *   1. wu_transition_{item}_{column}  – Fires when a column value changes.
 *   2. wu_pre_get_{items}             – Fires before items are fetched.
 *   3. wu_{items}_query_clauses       – Filters the SQL clauses.
 *   4. wu_parse_{items}_query         – Fires after query vars are parsed.
 *   5. wu_{items}_search_columns      – Filters the columns used for search.
 *   6. wu_the_{items}                 – Filters the found items.
 *   7. wu_filter_{item}_item          – Filters a single item.
 *   8. wu_found_{items}_query         – Filters the FOUND_ROWS() query.
 * ──────────────────────────────────────────────────────────────────────────────
 */

// ─── Membership ─────────────────────────────────────────────────────────────

/**
 * Fires when the status of a membership transitions from one value to another.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous membership status.
 * @param string $new_value The new membership status.
 * @param int    $item_id   The membership ID.
 */
do_action('wu_transition_membership_status', $old_value, $new_value, $item_id);

/**
 * Fires when the plan_id of a membership transitions from one value to another.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous plan ID.
 * @param int $new_value The new plan ID.
 * @param int $item_id   The membership ID.
 */
do_action('wu_transition_membership_plan_id', $old_value, $new_value, $item_id);

/**
 * Fires when the amount of a membership transitions from one value to another.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous amount.
 * @param string $new_value The new amount.
 * @param int    $item_id   The membership ID.
 */
do_action('wu_transition_membership_amount', $old_value, $new_value, $item_id);

/**
 * Fires when the initial_amount of a membership transitions from one value to another.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous initial amount.
 * @param string $new_value The new initial amount.
 * @param int    $item_id   The membership ID.
 */
do_action('wu_transition_membership_initial_amount', $old_value, $new_value, $item_id);

/**
 * Fires when the recurring flag of a membership transitions from one value to another.
 *
 * @since 2.0.0
 *
 * @param mixed $old_value The previous recurring value.
 * @param mixed $new_value The new recurring value.
 * @param int   $item_id   The membership ID.
 */
do_action('wu_transition_membership_recurring', $old_value, $new_value, $item_id);

/**
 * Fires when the auto_renew flag of a membership transitions from one value to another.
 *
 * @since 2.0.0
 *
 * @param mixed $old_value The previous auto_renew value.
 * @param mixed $new_value The new auto_renew value.
 * @param int   $item_id   The membership ID.
 */
do_action('wu_transition_membership_auto_renew', $old_value, $new_value, $item_id);

/**
 * Fires when the duration of a membership transitions from one value to another.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous duration.
 * @param int $new_value The new duration.
 * @param int $item_id   The membership ID.
 */
do_action('wu_transition_membership_duration', $old_value, $new_value, $item_id);

/**
 * Fires when the date_expiration of a membership transitions from one value to another.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous expiration date.
 * @param string $new_value The new expiration date.
 * @param int    $item_id   The membership ID.
 */
do_action('wu_transition_membership_date_expiration', $old_value, $new_value, $item_id);

/**
 * Fires when the date_payment_plan_completed of a membership transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous date.
 * @param string $new_value The new date.
 * @param int    $item_id   The membership ID.
 */
do_action('wu_transition_membership_date_payment_plan_completed', $old_value, $new_value, $item_id);

/**
 * Fires when times_billed of a membership transitions from one value to another.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous times_billed count.
 * @param int $new_value The new times_billed count.
 * @param int $item_id   The membership ID.
 */
do_action('wu_transition_membership_times_billed', $old_value, $new_value, $item_id);

/**
 * Fires when the gateway_customer_id of a membership transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous gateway customer ID.
 * @param string $new_value The new gateway customer ID.
 * @param int    $item_id   The membership ID.
 */
do_action('wu_transition_membership_gateway_customer_id', $old_value, $new_value, $item_id);

/**
 * Fires when the gateway_subscription_id of a membership transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous gateway subscription ID.
 * @param string $new_value The new gateway subscription ID.
 * @param int    $item_id   The membership ID.
 */
do_action('wu_transition_membership_gateway_subscription_id', $old_value, $new_value, $item_id);

/**
 * Fires before memberships are fetched from the database.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_pre_get_memberships', [&$query]);

/**
 * Filters the SQL clauses for a memberships query.
 *
 * @since 2.0.0
 *
 * @param array                    $clauses Associative array of SQL clauses.
 * @param \BerlinDB\Database\Query $query   The query instance (passed by reference).
 * @return array
 */
$clauses = apply_filters_ref_array('wu_memberships_query_clauses', [$clauses, &$query]);

/**
 * Fires after memberships query vars have been parsed.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_parse_memberships_query', [&$query]);

/**
 * Filters the columns to search when performing a memberships search.
 *
 * @since 2.0.0
 *
 * @param string[]                 $search_columns Array of column names to search.
 * @param string                   $search         The search term.
 * @param \BerlinDB\Database\Query $query          The query instance.
 * @return string[]
 */
$search_columns = apply_filters('wu_memberships_search_columns', $search_columns, $search, $query);

/**
 * Filters the found memberships after a query.
 *
 * @since 2.0.0
 *
 * @param object[]                 $items The array of found membership objects.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return object[]
 */
$items = apply_filters_ref_array('wu_the_memberships', [$items, &$query]);

/**
 * Filters a single membership item returned from the database.
 *
 * @since 2.0.0
 *
 * @param array                    $item  The raw database row as an array.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return array
 */
$item = apply_filters_ref_array('wu_filter_membership_item', [$item, &$query]);

/**
 * Filters the FOUND_ROWS() query for memberships.
 *
 * @since 2.0.0
 *
 * @param string                   $sql   The SQL query to count found rows.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return string
 */
$sql = apply_filters_ref_array('wu_found_memberships_query', [$sql, &$query]);

// ─── Payment ────────────────────────────────────────────────────────────────

/**
 * Fires when the status of a payment transitions from one value to another.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous payment status.
 * @param string $new_value The new payment status.
 * @param int    $item_id   The payment ID.
 */
do_action('wu_transition_payment_status', $old_value, $new_value, $item_id);

/**
 * Fires when the customer_id of a payment transitions.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous customer ID.
 * @param int $new_value The new customer ID.
 * @param int $item_id   The payment ID.
 */
do_action('wu_transition_payment_customer_id', $old_value, $new_value, $item_id);

/**
 * Fires when the membership_id of a payment transitions.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous membership ID.
 * @param int $new_value The new membership ID.
 * @param int $item_id   The payment ID.
 */
do_action('wu_transition_payment_membership_id', $old_value, $new_value, $item_id);

/**
 * Fires when the parent_id of a payment transitions.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous parent payment ID.
 * @param int $new_value The new parent payment ID.
 * @param int $item_id   The payment ID.
 */
do_action('wu_transition_payment_parent_id', $old_value, $new_value, $item_id);

/**
 * Fires when the product_id of a payment transitions.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous product ID.
 * @param int $new_value The new product ID.
 * @param int $item_id   The payment ID.
 */
do_action('wu_transition_payment_product_id', $old_value, $new_value, $item_id);

/**
 * Fires when the subtotal of a payment transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous subtotal.
 * @param string $new_value The new subtotal.
 * @param int    $item_id   The payment ID.
 */
do_action('wu_transition_payment_subtotal', $old_value, $new_value, $item_id);

/**
 * Fires when the refund_total of a payment transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous refund total.
 * @param string $new_value The new refund total.
 * @param int    $item_id   The payment ID.
 */
do_action('wu_transition_payment_refund_total', $old_value, $new_value, $item_id);

/**
 * Fires when the tax_total of a payment transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous tax total.
 * @param string $new_value The new tax total.
 * @param int    $item_id   The payment ID.
 */
do_action('wu_transition_payment_tax_total', $old_value, $new_value, $item_id);

/**
 * Fires when the total of a payment transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous total.
 * @param string $new_value The new total.
 * @param int    $item_id   The payment ID.
 */
do_action('wu_transition_payment_total', $old_value, $new_value, $item_id);

/**
 * Fires before payments are fetched from the database.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_pre_get_payments', [&$query]);

/**
 * Filters the SQL clauses for a payments query.
 *
 * @since 2.0.0
 *
 * @param array                    $clauses Associative array of SQL clauses.
 * @param \BerlinDB\Database\Query $query   The query instance (passed by reference).
 * @return array
 */
$clauses = apply_filters_ref_array('wu_payments_query_clauses', [$clauses, &$query]);

/**
 * Fires after payments query vars have been parsed.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_parse_payments_query', [&$query]);

/**
 * Filters the columns to search when performing a payments search.
 *
 * @since 2.0.0
 *
 * @param string[]                 $search_columns Array of column names to search.
 * @param string                   $search         The search term.
 * @param \BerlinDB\Database\Query $query          The query instance.
 * @return string[]
 */
$search_columns = apply_filters('wu_payments_search_columns', $search_columns, $search, $query);

/**
 * Filters the found payments after a query.
 *
 * @since 2.0.0
 *
 * @param object[]                 $items The array of found payment objects.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return object[]
 */
$items = apply_filters_ref_array('wu_the_payments', [$items, &$query]);

/**
 * Filters a single payment item returned from the database.
 *
 * @since 2.0.0
 *
 * @param array                    $item  The raw database row as an array.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return array
 */
$item = apply_filters_ref_array('wu_filter_payment_item', [$item, &$query]);

/**
 * Filters the FOUND_ROWS() query for payments.
 *
 * @since 2.0.0
 *
 * @param string                   $sql   The SQL query to count found rows.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return string
 */
$sql = apply_filters_ref_array('wu_found_payments_query', [$sql, &$query]);

// ─── Customer ───────────────────────────────────────────────────────────────

/**
 * Fires when the email_verification status of a customer transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous email verification status.
 * @param string $new_value The new email verification status.
 * @param int    $item_id   The customer ID.
 */
do_action('wu_transition_customer_email_verification', $old_value, $new_value, $item_id);

/**
 * Fires when the has_trialed flag of a customer transitions.
 *
 * @since 2.0.0
 *
 * @param mixed $old_value The previous has_trialed value.
 * @param mixed $new_value The new has_trialed value.
 * @param int   $item_id   The customer ID.
 */
do_action('wu_transition_customer_has_trialed', $old_value, $new_value, $item_id);

/**
 * Fires when the vip flag of a customer transitions.
 *
 * @since 2.0.0
 *
 * @param mixed $old_value The previous vip value.
 * @param mixed $new_value The new vip value.
 * @param int   $item_id   The customer ID.
 */
do_action('wu_transition_customer_vip', $old_value, $new_value, $item_id);

/**
 * Fires before customers are fetched from the database.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_pre_get_customers', [&$query]);

/**
 * Filters the SQL clauses for a customers query.
 *
 * @since 2.0.0
 *
 * @param array                    $clauses Associative array of SQL clauses.
 * @param \BerlinDB\Database\Query $query   The query instance (passed by reference).
 * @return array
 */
$clauses = apply_filters_ref_array('wu_customers_query_clauses', [$clauses, &$query]);

/**
 * Fires after customers query vars have been parsed.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_parse_customers_query', [&$query]);

/**
 * Filters the columns to search when performing a customers search.
 *
 * @since 2.0.0
 *
 * @param string[]                 $search_columns Array of column names to search.
 * @param string                   $search         The search term.
 * @param \BerlinDB\Database\Query $query          The query instance.
 * @return string[]
 */
$search_columns = apply_filters('wu_customers_search_columns', $search_columns, $search, $query);

/**
 * Filters the found customers after a query.
 *
 * @since 2.0.0
 *
 * @param object[]                 $items The array of found customer objects.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return object[]
 */
$items = apply_filters_ref_array('wu_the_customers', [$items, &$query]);

/**
 * Filters a single customer item returned from the database.
 *
 * @since 2.0.0
 *
 * @param array                    $item  The raw database row as an array.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return array
 */
$item = apply_filters_ref_array('wu_filter_customer_item', [$item, &$query]);

/**
 * Filters the FOUND_ROWS() query for customers.
 *
 * @since 2.0.0
 *
 * @param string                   $sql   The SQL query to count found rows.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return string
 */
$sql = apply_filters_ref_array('wu_found_customers_query', [$sql, &$query]);

// ─── Product ────────────────────────────────────────────────────────────────

/**
 * Fires when the active flag of a product transitions.
 *
 * @since 2.0.0
 *
 * @param mixed $old_value The previous active value.
 * @param mixed $new_value The new active value.
 * @param int   $item_id   The product ID.
 */
do_action('wu_transition_product_active', $old_value, $new_value, $item_id);

/**
 * Fires when the amount of a product transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous amount.
 * @param string $new_value The new amount.
 * @param int    $item_id   The product ID.
 */
do_action('wu_transition_product_amount', $old_value, $new_value, $item_id);

/**
 * Fires when the setup_fee of a product transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous setup fee.
 * @param string $new_value The new setup fee.
 * @param int    $item_id   The product ID.
 */
do_action('wu_transition_product_setup_fee', $old_value, $new_value, $item_id);

/**
 * Fires when the recurring flag of a product transitions.
 *
 * @since 2.0.0
 *
 * @param mixed $old_value The previous recurring value.
 * @param mixed $new_value The new recurring value.
 * @param int   $item_id   The product ID.
 */
do_action('wu_transition_product_recurring', $old_value, $new_value, $item_id);

/**
 * Fires when the trial_duration of a product transitions.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous trial duration.
 * @param int $new_value The new trial duration.
 * @param int $item_id   The product ID.
 */
do_action('wu_transition_product_trial_duration', $old_value, $new_value, $item_id);

/**
 * Fires when the duration of a product transitions.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous duration.
 * @param int $new_value The new duration.
 * @param int $item_id   The product ID.
 */
do_action('wu_transition_product_duration', $old_value, $new_value, $item_id);

/**
 * Fires when the billing_cycles of a product transitions.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous billing cycles count.
 * @param int $new_value The new billing cycles count.
 * @param int $item_id   The product ID.
 */
do_action('wu_transition_product_billing_cycles', $old_value, $new_value, $item_id);

/**
 * Fires when the list_order of a product transitions.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous list order.
 * @param int $new_value The new list order.
 * @param int $item_id   The product ID.
 */
do_action('wu_transition_product_list_order', $old_value, $new_value, $item_id);

/**
 * Fires when the parent_id of a product transitions.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous parent ID.
 * @param int $new_value The new parent ID.
 * @param int $item_id   The product ID.
 */
do_action('wu_transition_product_parent_id', $old_value, $new_value, $item_id);

/**
 * Fires before products are fetched from the database.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_pre_get_products', [&$query]);

/**
 * Filters the SQL clauses for a products query.
 *
 * @since 2.0.0
 *
 * @param array                    $clauses Associative array of SQL clauses.
 * @param \BerlinDB\Database\Query $query   The query instance (passed by reference).
 * @return array
 */
$clauses = apply_filters_ref_array('wu_products_query_clauses', [$clauses, &$query]);

/**
 * Fires after products query vars have been parsed.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_parse_products_query', [&$query]);

/**
 * Filters the columns to search when performing a products search.
 *
 * @since 2.0.0
 *
 * @param string[]                 $search_columns Array of column names to search.
 * @param string                   $search         The search term.
 * @param \BerlinDB\Database\Query $query          The query instance.
 * @return string[]
 */
$search_columns = apply_filters('wu_products_search_columns', $search_columns, $search, $query);

/**
 * Filters the found products after a query.
 *
 * @since 2.0.0
 *
 * @param object[]                 $items The array of found product objects.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return object[]
 */
$items = apply_filters_ref_array('wu_the_products', [$items, &$query]);

/**
 * Filters a single product item returned from the database.
 *
 * @since 2.0.0
 *
 * @param array                    $item  The raw database row as an array.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return array
 */
$item = apply_filters_ref_array('wu_filter_product_item', [$item, &$query]);

/**
 * Filters the FOUND_ROWS() query for products.
 *
 * @since 2.0.0
 *
 * @param string                   $sql   The SQL query to count found rows.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return string
 */
$sql = apply_filters_ref_array('wu_found_products_query', [$sql, &$query]);

// ─── Domain ─────────────────────────────────────────────────────────────────

/**
 * Fires when the domain value of a domain mapping transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous domain name.
 * @param string $new_value The new domain name.
 * @param int    $item_id   The domain ID.
 */
do_action('wu_transition_domain_domain', $old_value, $new_value, $item_id);

/**
 * Fires when the active flag of a domain transitions.
 *
 * @since 2.0.0
 *
 * @param mixed $old_value The previous active value.
 * @param mixed $new_value The new active value.
 * @param int   $item_id   The domain ID.
 */
do_action('wu_transition_domain_active', $old_value, $new_value, $item_id);

/**
 * Fires when the primary_domain flag of a domain transitions.
 *
 * @since 2.0.0
 *
 * @param mixed $old_value The previous primary_domain value.
 * @param mixed $new_value The new primary_domain value.
 * @param int   $item_id   The domain ID.
 */
do_action('wu_transition_domain_primary_domain', $old_value, $new_value, $item_id);

/**
 * Fires when the secure flag of a domain transitions.
 *
 * @since 2.0.0
 *
 * @param mixed $old_value The previous secure value.
 * @param mixed $new_value The new secure value.
 * @param int   $item_id   The domain ID.
 */
do_action('wu_transition_domain_secure', $old_value, $new_value, $item_id);

/**
 * Fires when the stage of a domain transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous stage value.
 * @param string $new_value The new stage value.
 * @param int    $item_id   The domain ID.
 */
do_action('wu_transition_domain_stage', $old_value, $new_value, $item_id);

/**
 * Fires before domains are fetched from the database.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_pre_get_domains', [&$query]);

/**
 * Filters the SQL clauses for a domains query.
 *
 * @since 2.0.0
 *
 * @param array                    $clauses Associative array of SQL clauses.
 * @param \BerlinDB\Database\Query $query   The query instance (passed by reference).
 * @return array
 */
$clauses = apply_filters_ref_array('wu_domains_query_clauses', [$clauses, &$query]);

/**
 * Fires after domains query vars have been parsed.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_parse_domains_query', [&$query]);

/**
 * Filters the columns to search when performing a domains search.
 *
 * @since 2.0.0
 *
 * @param string[]                 $search_columns Array of column names to search.
 * @param string                   $search         The search term.
 * @param \BerlinDB\Database\Query $query          The query instance.
 * @return string[]
 */
$search_columns = apply_filters('wu_domains_search_columns', $search_columns, $search, $query);

/**
 * Filters the found domains after a query.
 *
 * @since 2.0.0
 *
 * @param object[]                 $items The array of found domain objects.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return object[]
 */
$items = apply_filters_ref_array('wu_the_domains', [$items, &$query]);

/**
 * Filters a single domain item returned from the database.
 *
 * @since 2.0.0
 *
 * @param array                    $item  The raw database row as an array.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return array
 */
$item = apply_filters_ref_array('wu_filter_domain_item', [$item, &$query]);

/**
 * Filters the FOUND_ROWS() query for domains.
 *
 * @since 2.0.0
 *
 * @param string                   $sql   The SQL query to count found rows.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return string
 */
$sql = apply_filters_ref_array('wu_found_domains_query', [$sql, &$query]);

// ─── Discount Code ──────────────────────────────────────────────────────────

/**
 * Fires when the active flag of a discount code transitions.
 *
 * @since 2.0.0
 *
 * @param mixed $old_value The previous active value.
 * @param mixed $new_value The new active value.
 * @param int   $item_id   The discount code ID.
 */
do_action('wu_transition_discount_code_active', $old_value, $new_value, $item_id);

/**
 * Fires when the code of a discount code transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous code.
 * @param string $new_value The new code.
 * @param int    $item_id   The discount code ID.
 */
do_action('wu_transition_discount_code_code', $old_value, $new_value, $item_id);

/**
 * Fires when the uses count of a discount code transitions.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous uses count.
 * @param int $new_value The new uses count.
 * @param int $item_id   The discount code ID.
 */
do_action('wu_transition_discount_code_uses', $old_value, $new_value, $item_id);

/**
 * Fires when the max_uses of a discount code transitions.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous max_uses value.
 * @param int $new_value The new max_uses value.
 * @param int $item_id   The discount code ID.
 */
do_action('wu_transition_discount_code_max_uses', $old_value, $new_value, $item_id);

/**
 * Fires when the apply_to_renewals flag of a discount code transitions.
 *
 * @since 2.0.0
 *
 * @param mixed $old_value The previous apply_to_renewals value.
 * @param mixed $new_value The new apply_to_renewals value.
 * @param int   $item_id   The discount code ID.
 */
do_action('wu_transition_discount_code_apply_to_renewals', $old_value, $new_value, $item_id);

/**
 * Fires when the type of a discount code transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous type (e.g. percentage, absolute).
 * @param string $new_value The new type.
 * @param int    $item_id   The discount code ID.
 */
do_action('wu_transition_discount_code_type', $old_value, $new_value, $item_id);

/**
 * Fires when the value of a discount code transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous discount value.
 * @param string $new_value The new discount value.
 * @param int    $item_id   The discount code ID.
 */
do_action('wu_transition_discount_code_value', $old_value, $new_value, $item_id);

/**
 * Fires when the setup_fee_type of a discount code transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous setup fee type.
 * @param string $new_value The new setup fee type.
 * @param int    $item_id   The discount code ID.
 */
do_action('wu_transition_discount_code_setup_fee_type', $old_value, $new_value, $item_id);

/**
 * Fires when the setup_fee_value of a discount code transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous setup fee value.
 * @param string $new_value The new setup fee value.
 * @param int    $item_id   The discount code ID.
 */
do_action('wu_transition_discount_code_setup_fee_value', $old_value, $new_value, $item_id);

/**
 * Fires when the date_start of a discount code transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous start date.
 * @param string $new_value The new start date.
 * @param int    $item_id   The discount code ID.
 */
do_action('wu_transition_discount_code_date_start', $old_value, $new_value, $item_id);

/**
 * Fires when the date_expiration of a discount code transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous expiration date.
 * @param string $new_value The new expiration date.
 * @param int    $item_id   The discount code ID.
 */
do_action('wu_transition_discount_code_date_expiration', $old_value, $new_value, $item_id);

/**
 * Fires before discount codes are fetched from the database.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_pre_get_discount_codes', [&$query]);

/**
 * Filters the SQL clauses for a discount codes query.
 *
 * @since 2.0.0
 *
 * @param array                    $clauses Associative array of SQL clauses.
 * @param \BerlinDB\Database\Query $query   The query instance (passed by reference).
 * @return array
 */
$clauses = apply_filters_ref_array('wu_discount_codes_query_clauses', [$clauses, &$query]);

/**
 * Fires after discount codes query vars have been parsed.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_parse_discount_codes_query', [&$query]);

/**
 * Filters the columns to search when performing a discount codes search.
 *
 * @since 2.0.0
 *
 * @param string[]                 $search_columns Array of column names to search.
 * @param string                   $search         The search term.
 * @param \BerlinDB\Database\Query $query          The query instance.
 * @return string[]
 */
$search_columns = apply_filters('wu_discount_codes_search_columns', $search_columns, $search, $query);

/**
 * Filters the found discount codes after a query.
 *
 * @since 2.0.0
 *
 * @param object[]                 $items The array of found discount code objects.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return object[]
 */
$items = apply_filters_ref_array('wu_the_discount_codes', [$items, &$query]);

/**
 * Filters a single discount code item returned from the database.
 *
 * @since 2.0.0
 *
 * @param array                    $item  The raw database row as an array.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return array
 */
$item = apply_filters_ref_array('wu_filter_discount_code_item', [$item, &$query]);

/**
 * Filters the FOUND_ROWS() query for discount codes.
 *
 * @since 2.0.0
 *
 * @param string                   $sql   The SQL query to count found rows.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return string
 */
$sql = apply_filters_ref_array('wu_found_discount_codes_query', [$sql, &$query]);

// ─── Site (Blog) ────────────────────────────────────────────────────────────

/**
 * Fires before sites (blogs) are fetched from the database.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_pre_get_blogs', [&$query]);

/**
 * Filters the SQL clauses for a sites (blogs) query.
 *
 * @since 2.0.0
 *
 * @param array                    $clauses Associative array of SQL clauses.
 * @param \BerlinDB\Database\Query $query   The query instance (passed by reference).
 * @return array
 */
$clauses = apply_filters_ref_array('wu_blogs_query_clauses', [$clauses, &$query]);

/**
 * Fires after sites (blogs) query vars have been parsed.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_parse_blogs_query', [&$query]);

/**
 * Filters the columns to search when performing a sites (blogs) search.
 *
 * @since 2.0.0
 *
 * @param string[]                 $search_columns Array of column names to search.
 * @param string                   $search         The search term.
 * @param \BerlinDB\Database\Query $query          The query instance.
 * @return string[]
 */
$search_columns = apply_filters('wu_blogs_search_columns', $search_columns, $search, $query);

/**
 * Filters the found sites (blogs) after a query.
 *
 * @since 2.0.0
 *
 * @param object[]                 $items The array of found site objects.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return object[]
 */
$items = apply_filters_ref_array('wu_the_blogs', [$items, &$query]);

/**
 * Filters a single site (blog) item returned from the database.
 *
 * @since 2.0.0
 *
 * @param array                    $item  The raw database row as an array.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return array
 */
$item = apply_filters_ref_array('wu_filter_blog_item', [$item, &$query]);

/**
 * Filters the FOUND_ROWS() query for sites (blogs).
 *
 * @since 2.0.0
 *
 * @param string                   $sql   The SQL query to count found rows.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return string
 */
$sql = apply_filters_ref_array('wu_found_blogs_query', [$sql, &$query]);

// ─── Broadcast ──────────────────────────────────────────────────────────────

/**
 * Fires before broadcasts are fetched from the database.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_pre_get_broadcasts', [&$query]);

/**
 * Filters the SQL clauses for a broadcasts query.
 *
 * @since 2.0.0
 *
 * @param array                    $clauses Associative array of SQL clauses.
 * @param \BerlinDB\Database\Query $query   The query instance (passed by reference).
 * @return array
 */
$clauses = apply_filters_ref_array('wu_broadcasts_query_clauses', [$clauses, &$query]);

/**
 * Fires after broadcasts query vars have been parsed.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_parse_broadcasts_query', [&$query]);

/**
 * Filters the columns to search when performing a broadcasts search.
 *
 * @since 2.0.0
 *
 * @param string[]                 $search_columns Array of column names to search.
 * @param string                   $search         The search term.
 * @param \BerlinDB\Database\Query $query          The query instance.
 * @return string[]
 */
$search_columns = apply_filters('wu_broadcasts_search_columns', $search_columns, $search, $query);

/**
 * Filters the found broadcasts after a query.
 *
 * @since 2.0.0
 *
 * @param object[]                 $items The array of found broadcast objects.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return object[]
 */
$items = apply_filters_ref_array('wu_the_broadcasts', [$items, &$query]);

/**
 * Filters a single broadcast item returned from the database.
 *
 * @since 2.0.0
 *
 * @param array                    $item  The raw database row as an array.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return array
 */
$item = apply_filters_ref_array('wu_filter_broadcast_item', [$item, &$query]);

/**
 * Filters the FOUND_ROWS() query for broadcasts.
 *
 * @since 2.0.0
 *
 * @param string                   $sql   The SQL query to count found rows.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return string
 */
$sql = apply_filters_ref_array('wu_found_broadcasts_query', [$sql, &$query]);

// ─── Email ──────────────────────────────────────────────────────────────────

/**
 * Fires before emails are fetched from the database.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_pre_get_emails', [&$query]);

/**
 * Filters the SQL clauses for an emails query.
 *
 * @since 2.0.0
 *
 * @param array                    $clauses Associative array of SQL clauses.
 * @param \BerlinDB\Database\Query $query   The query instance (passed by reference).
 * @return array
 */
$clauses = apply_filters_ref_array('wu_emails_query_clauses', [$clauses, &$query]);

/**
 * Fires after emails query vars have been parsed.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_parse_emails_query', [&$query]);

/**
 * Filters the columns to search when performing an emails search.
 *
 * @since 2.0.0
 *
 * @param string[]                 $search_columns Array of column names to search.
 * @param string                   $search         The search term.
 * @param \BerlinDB\Database\Query $query          The query instance.
 * @return string[]
 */
$search_columns = apply_filters('wu_emails_search_columns', $search_columns, $search, $query);

/**
 * Filters the found emails after a query.
 *
 * @since 2.0.0
 *
 * @param object[]                 $items The array of found email objects.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return object[]
 */
$items = apply_filters_ref_array('wu_the_emails', [$items, &$query]);

/**
 * Filters a single email item returned from the database.
 *
 * @since 2.0.0
 *
 * @param array                    $item  The raw database row as an array.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return array
 */
$item = apply_filters_ref_array('wu_filter_email_item', [$item, &$query]);

/**
 * Filters the FOUND_ROWS() query for emails.
 *
 * @since 2.0.0
 *
 * @param string                   $sql   The SQL query to count found rows.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return string
 */
$sql = apply_filters_ref_array('wu_found_emails_query', [$sql, &$query]);

// ─── Event ──────────────────────────────────────────────────────────────────

/**
 * Fires when the author_id of an event transitions.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous author ID.
 * @param int $new_value The new author ID.
 * @param int $item_id   The event ID.
 */
do_action('wu_transition_event_author_id', $old_value, $new_value, $item_id);

/**
 * Fires when the object_id of an event transitions.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous object ID.
 * @param int $new_value The new object ID.
 * @param int $item_id   The event ID.
 */
do_action('wu_transition_event_object_id', $old_value, $new_value, $item_id);

/**
 * Fires before events are fetched from the database.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_pre_get_events', [&$query]);

/**
 * Filters the SQL clauses for an events query.
 *
 * @since 2.0.0
 *
 * @param array                    $clauses Associative array of SQL clauses.
 * @param \BerlinDB\Database\Query $query   The query instance (passed by reference).
 * @return array
 */
$clauses = apply_filters_ref_array('wu_events_query_clauses', [$clauses, &$query]);

/**
 * Fires after events query vars have been parsed.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_parse_events_query', [&$query]);

/**
 * Filters the columns to search when performing an events search.
 *
 * @since 2.0.0
 *
 * @param string[]                 $search_columns Array of column names to search.
 * @param string                   $search         The search term.
 * @param \BerlinDB\Database\Query $query          The query instance.
 * @return string[]
 */
$search_columns = apply_filters('wu_events_search_columns', $search_columns, $search, $query);

/**
 * Filters the found events after a query.
 *
 * @since 2.0.0
 *
 * @param object[]                 $items The array of found event objects.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return object[]
 */
$items = apply_filters_ref_array('wu_the_events', [$items, &$query]);

/**
 * Filters a single event item returned from the database.
 *
 * @since 2.0.0
 *
 * @param array                    $item  The raw database row as an array.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return array
 */
$item = apply_filters_ref_array('wu_filter_event_item', [$item, &$query]);

/**
 * Filters the FOUND_ROWS() query for events.
 *
 * @since 2.0.0
 *
 * @param string                   $sql   The SQL query to count found rows.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return string
 */
$sql = apply_filters_ref_array('wu_found_events_query', [$sql, &$query]);

// ─── Webhook ────────────────────────────────────────────────────────────────

/**
 * Fires when the active flag of a webhook transitions.
 *
 * @since 2.0.0
 *
 * @param mixed $old_value The previous active value.
 * @param mixed $new_value The new active value.
 * @param int   $item_id   The webhook ID.
 */
do_action('wu_transition_webhook_active', $old_value, $new_value, $item_id);

/**
 * Fires when the hidden flag of a webhook transitions.
 *
 * @since 2.0.0
 *
 * @param mixed $old_value The previous hidden value.
 * @param mixed $new_value The new hidden value.
 * @param int   $item_id   The webhook ID.
 */
do_action('wu_transition_webhook_hidden', $old_value, $new_value, $item_id);

/**
 * Fires before webhooks are fetched from the database.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_pre_get_webhooks', [&$query]);

/**
 * Filters the SQL clauses for a webhooks query.
 *
 * @since 2.0.0
 *
 * @param array                    $clauses Associative array of SQL clauses.
 * @param \BerlinDB\Database\Query $query   The query instance (passed by reference).
 * @return array
 */
$clauses = apply_filters_ref_array('wu_webhooks_query_clauses', [$clauses, &$query]);

/**
 * Fires after webhooks query vars have been parsed.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_parse_webhooks_query', [&$query]);

/**
 * Filters the columns to search when performing a webhooks search.
 *
 * @since 2.0.0
 *
 * @param string[]                 $search_columns Array of column names to search.
 * @param string                   $search         The search term.
 * @param \BerlinDB\Database\Query $query          The query instance.
 * @return string[]
 */
$search_columns = apply_filters('wu_webhooks_search_columns', $search_columns, $search, $query);

/**
 * Filters the found webhooks after a query.
 *
 * @since 2.0.0
 *
 * @param object[]                 $items The array of found webhook objects.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return object[]
 */
$items = apply_filters_ref_array('wu_the_webhooks', [$items, &$query]);

/**
 * Filters a single webhook item returned from the database.
 *
 * @since 2.0.0
 *
 * @param array                    $item  The raw database row as an array.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return array
 */
$item = apply_filters_ref_array('wu_filter_webhook_item', [$item, &$query]);

/**
 * Filters the FOUND_ROWS() query for webhooks.
 *
 * @since 2.0.0
 *
 * @param string                   $sql   The SQL query to count found rows.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return string
 */
$sql = apply_filters_ref_array('wu_found_webhooks_query', [$sql, &$query]);

// ─── Checkout Form ──────────────────────────────────────────────────────────

/**
 * Fires when the name of a checkout form transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous name.
 * @param string $new_value The new name.
 * @param int    $item_id   The checkout form ID.
 */
do_action('wu_transition_checkout_form_name', $old_value, $new_value, $item_id);

/**
 * Fires when the slug of a checkout form transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous slug.
 * @param string $new_value The new slug.
 * @param int    $item_id   The checkout form ID.
 */
do_action('wu_transition_checkout_form_slug', $old_value, $new_value, $item_id);

/**
 * Fires when the active flag of a checkout form transitions.
 *
 * @since 2.0.0
 *
 * @param mixed $old_value The previous active value.
 * @param mixed $new_value The new active value.
 * @param int   $item_id   The checkout form ID.
 */
do_action('wu_transition_checkout_form_active', $old_value, $new_value, $item_id);

/**
 * Fires when the settings of a checkout form transitions.
 *
 * @since 2.0.0
 *
 * @param mixed $old_value The previous settings value.
 * @param mixed $new_value The new settings value.
 * @param int   $item_id   The checkout form ID.
 */
do_action('wu_transition_checkout_form_settings', $old_value, $new_value, $item_id);

/**
 * Fires before checkout forms are fetched from the database.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_pre_get_checkout_forms', [&$query]);

/**
 * Filters the SQL clauses for a checkout forms query.
 *
 * @since 2.0.0
 *
 * @param array                    $clauses Associative array of SQL clauses.
 * @param \BerlinDB\Database\Query $query   The query instance (passed by reference).
 * @return array
 */
$clauses = apply_filters_ref_array('wu_checkout_forms_query_clauses', [$clauses, &$query]);

/**
 * Fires after checkout forms query vars have been parsed.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_parse_checkout_forms_query', [&$query]);

/**
 * Filters the columns to search when performing a checkout forms search.
 *
 * @since 2.0.0
 *
 * @param string[]                 $search_columns Array of column names to search.
 * @param string                   $search         The search term.
 * @param \BerlinDB\Database\Query $query          The query instance.
 * @return string[]
 */
$search_columns = apply_filters('wu_checkout_forms_search_columns', $search_columns, $search, $query);

/**
 * Filters the found checkout forms after a query.
 *
 * @since 2.0.0
 *
 * @param object[]                 $items The array of found checkout form objects.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return object[]
 */
$items = apply_filters_ref_array('wu_the_checkout_forms', [$items, &$query]);

/**
 * Filters a single checkout form item returned from the database.
 *
 * @since 2.0.0
 *
 * @param array                    $item  The raw database row as an array.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return array
 */
$item = apply_filters_ref_array('wu_filter_checkout_form_item', [$item, &$query]);

/**
 * Filters the FOUND_ROWS() query for checkout forms.
 *
 * @since 2.0.0
 *
 * @param string                   $sql   The SQL query to count found rows.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return string
 */
$sql = apply_filters_ref_array('wu_found_checkout_forms_query', [$sql, &$query]);

// ─── Post (Broadcast/Email base) ────────────────────────────────────────────

/**
 * Fires when the status of a post transitions.
 *
 * @since 2.0.0
 *
 * @param string $old_value The previous status.
 * @param string $new_value The new status.
 * @param int    $item_id   The post ID.
 */
do_action('wu_transition_post_status', $old_value, $new_value, $item_id);

/**
 * Fires when the list_order of a post transitions.
 *
 * @since 2.0.0
 *
 * @param int $old_value The previous list order.
 * @param int $new_value The new list order.
 * @param int $item_id   The post ID.
 */
do_action('wu_transition_post_list_order', $old_value, $new_value, $item_id);

/**
 * Fires before posts are fetched from the database.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_pre_get_posts', [&$query]);

/**
 * Filters the SQL clauses for a posts query.
 *
 * @since 2.0.0
 *
 * @param array                    $clauses Associative array of SQL clauses.
 * @param \BerlinDB\Database\Query $query   The query instance (passed by reference).
 * @return array
 */
$clauses = apply_filters_ref_array('wu_posts_query_clauses', [$clauses, &$query]);

/**
 * Fires after posts query vars have been parsed.
 *
 * @since 2.0.0
 *
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 */
do_action_ref_array('wu_parse_posts_query', [&$query]);

/**
 * Filters the columns to search when performing a posts search.
 *
 * @since 2.0.0
 *
 * @param string[]                 $search_columns Array of column names to search.
 * @param string                   $search         The search term.
 * @param \BerlinDB\Database\Query $query          The query instance.
 * @return string[]
 */
$search_columns = apply_filters('wu_posts_search_columns', $search_columns, $search, $query);

/**
 * Filters the found posts after a query.
 *
 * @since 2.0.0
 *
 * @param object[]                 $items The array of found post objects.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return object[]
 */
$items = apply_filters_ref_array('wu_the_posts', [$items, &$query]);

/**
 * Filters a single post item returned from the database.
 *
 * @since 2.0.0
 *
 * @param array                    $item  The raw database row as an array.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return array
 */
$item = apply_filters_ref_array('wu_filter_post_item', [$item, &$query]);

/**
 * Filters the FOUND_ROWS() query for posts.
 *
 * @since 2.0.0
 *
 * @param string                   $sql   The SQL query to count found rows.
 * @param \BerlinDB\Database\Query $query The query instance (passed by reference).
 * @return string
 */
$sql = apply_filters_ref_array('wu_found_posts_query', [$sql, &$query]);

// phpcs:enable
